# Generated by Django 5.1.4 on 2025-01-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted_api', '0002_category_parent_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
